# Generated by Django 3.1.2 on 2021-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20210113_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/no-image.jpg', upload_to='network/images/'),
        ),
    ]
